// HANDLES SCORING AND DISPLAYS IT ON SCREEN

#pragma strict

// STATIC VARIABLES SO WE CAN ACCESS THEM FROM A STATIC FUNCTION

static var playerScore01 : int = 0; // SCORE FOR PLAYER01
static var playerScore02 : int = 0; // SCORE FOR PLAYER02

// CALL static FUNCTION FROM ANY OBJECT IN OUR SCREEN

// () > TAKES IN A PARAMETER FOR FINDING OUT WAS IT THE RIGHT WALL OR THE LEFT WALL THAT THE BALL HIT
// CHANGE THE SCORE FOR THE PLAYER OPPOSITE TO IT
/* PARAMETER THAT WILL STORE THE NAME OF THE OBJECT THAT CALLED THIS FUNCTION. THEN WE CAN DETERMINE WHAT 
VALUE WE WANT CHANGED. WHENEVER THIS FUNCTION GETS CALLED, WE WANT TO HAVE THE PARAMETER OF TYPE STRING */

static function Score (wallName : String)
{
	if (wallName == "rightWall")
	{
		playerScore01 += 1; // +1 TO THE CORRECT VARIABLE
	}
	
	else
	{
		playerScore02 += 1;
	}
	
	Debug.Log("Player Score 1 is " + playerScore01); // ALLOW US TO QUICKLY SEE
	Debug.Log("Player Score 2 is " + playerScore02); // WHAT IS THE CURRENT SCORE
}

function OnGUI() // STORES ALL THE GUI STUFF
{
	/* MAKES 2 Labels WHICH WILL BOTH GO TO CENTRE OF SCREEN HRIZONTAL ANXOS AND SUBTRACT 150 FROM PLAYER01 AND
	AND ADD 150 TO PLAYER02 */
	
	GUI.Label(new Rect(Screen.width/2-150, 20, 100, 100), "P1: " + playerScore01);
	GUI.Label(new Rect(Screen.width/2+150, 20, 100, 100), "P2: " + playerScore02);
}