/* A FUNCTION THAT IS CALLED EVERY TIME A HIT TRIGGERS AND WHENEVER THE BALL PASSES THROUGH A SIDEWALL */

#pragma strict

// () > STORES INFO REGARDS TO WHAT HIT US
function OnTriggerEnter2D (hitInfo : Collider2D) 
{
	/* ONLY MEANT TO CALL THIS IF IT'S THE BALL THAT HITS THE WALL. 
	
	WHEN THAT HAPPENS, THE INFO. IS SENT TO OUR GameManager THAT Score SHOULD BE CALLED 
	
	WE CAN DO THIS VERY SIMPLY SINCE WE HAVE A STATIC FUNCTION AND HENCE WE CAN EASILY CALL IT AND THEN 
	WE'RE GOING TO SEND OVER A VARIABLE WHICH WE DECLARE AS wallName */ 
	
	if (hitInfo.name === "Ball")
	{
		/* ONCE OUR BALL HITS THE TRIGGER, IT CHECKS IF IT IS THE BALL OR NOT.
		
		IF IT IS THEN IT SENDS OUR GameManager TELLING IT TO CALL THE FUNCTION Score WITH THE wallName
		
		THEN IT GETS THROWN OVER TO THE IF STATMENT OF THE GameManager WHICH CHECKS WHICH PLAYER SCORED 
		AND WHOEVER DID, THEIR SCORE GOES UP BY 1 */ 
		
		var wallName = transform.name;
		GameManager.Score(wallName);
		
		hitInfo.gameObject.SendMessage("ResetBall"); // TO RESET THE BALL WHEN THE SIDE WALLS ARE HIT
	}
}